<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>WorldBoxMultiplayer</AssemblyName>
    <RootNamespace>WorldBoxMultiplayer</RootNamespace>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>0.3.0</Version>
    <OutputType>Library</OutputType>
    <GameData>$(WorldBoxDir)/worldbox_Data/Managed</GameData>
    <BepInExDir>$(WorldBoxDir)/BepInEx/core</BepInExDir>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Steamworks.NET" Version="20.2.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>$(BepInExDir)/BepInEx.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameData)/UnityEngine.CoreModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>$(GameData)/UnityEngine.InputLegacyModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(GameData)/UnityEngine.IMGUIModule.dll</HintPath><Private>False</Private></Reference>
  </ItemGroup>
</Project>
